BTT3:
  prep_time: 3
  exec_time: 10
  objects: 67
  decoys: 5
  tables: 6
  shelfes_grasping: 2
  shelfes_placing: 1
  arbitrary_surfaces: 2
  obstacles: 2
  barrier_tapes: 1
  container_placing_r: 2
  container_placing_b: 2
  paired_containers: 1
