arena:
  workstations:
    WS01: "10"
    WS02: "10"
    WS03: "00"
    WS04: "15"
    WS05: "15"
    WS06: "00"
    WS07: "00"
    WS08: "10"
    WS09: "10"
    WS10: "05"
    WS11: "05"
    WS12: "15"
    SH01: "SH"
    SH02: "SH"
    PP01: "PP"
    TT01: "TT"
  objects:
    F20_20_G      : 5
    F20_20_B      : 5
    S40_40_B      : 5
    S40_40_G      : 5
    M20           : 5
    M30           : 5
    M20_100       : 5
    Axis2         : 0
    Bearing2      : 0
    Housing       : 0
    Motor2        : 0
    Spacer        : 0
    Screwdriver   : 0
    Wrench        : 0
    Drill         : 0
    AllenKey      : 0
    CONTAINER_RED :  2
    CONTAINER_BLUE:  2
  cavities: [ "F20_20_H", "S40_40_H", "M20_H", "M30_H", "M20_100_H", "R20_H", "F20_20_V", "S40_40_V", "M20_V", "M30_V", "R20_V" ]
